name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CONAN_V2_MODE: 1

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  # Build and test on multiple platforms
  build-and-test:
    name: Build & Test (${{ matrix.os }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-22.04
            compiler: gcc-11
            arch: x86_64
            build_type: Release
            conan_profile: default
          - os: ubuntu-22.04
            compiler: clang-14
            arch: x86_64
            build_type: Debug
            conan_profile: default
          # macOS builds
          - os: macos-14
            compiler: apple-clang
            arch: arm64
            build_type: Release
            conan_profile: default
          - os: macos-14
            compiler: apple-clang
            arch: x86_64
            build_type: Debug
            conan_profile: default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Setup Python for Conan
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install Conan
    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan==2.0.16

    # Setup compiler based on platform
    - name: Setup GCC (Linux)
      if: runner.os == 'Linux' && matrix.compiler == 'gcc-11'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-11 g++-11
        echo "CC=gcc-11" >> $GITHUB_ENV
        echo "CXX=g++-11" >> $GITHUB_ENV

    - name: Setup Clang (Linux)
      if: runner.os == 'Linux' && matrix.compiler == 'clang-14'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-14
        echo "CC=clang-14" >> $GITHUB_ENV
        echo "CXX=clang++-14" >> $GITHUB_ENV

    - name: Setup Xcode (macOS)
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    # Create Conan profile
    - name: Create Conan profile
      run: |
        conan profile detect --force

        # Create custom profile
        echo '[settings]' > custom_profile
        echo "os=${{ runner.os == 'Linux' && 'Linux' || 'Macos' }}" >> custom_profile
        echo "arch=${{ matrix.arch == 'arm64' && 'armv8' || 'x86_64' }}" >> custom_profile
        echo "compiler=${{ matrix.compiler == 'gcc-11' && 'gcc' || matrix.compiler == 'clang-14' && 'clang' || 'apple-clang' }}" >> custom_profile
        echo "compiler.version=${{ matrix.compiler == 'gcc-11' && '11' || matrix.compiler == 'clang-14' && '14' || '14' }}" >> custom_profile
        echo "compiler.cppstd=20" >> custom_profile
        echo "compiler.libcxx=${{ matrix.compiler == 'gcc-11' && 'libstdc++11' || matrix.compiler == 'clang-14' && 'libstdc++11' || 'libc++' }}" >> custom_profile
        echo "build_type=${{ matrix.build_type }}" >> custom_profile
        echo '' >> custom_profile
        echo '[conf]' >> custom_profile
        echo 'tools.cmake.cmaketoolchain:generator=Ninja' >> custom_profile

        # Show the created profile (optional)
        cat custom_profile

    # Install dependencies with Conan
    - name: Install dependencies
      run: |
        conan install . --build=missing --profile:build=custom_profile --profile:host=custom_profile

        # Copy CMakePresets.json and conan_toolchain to root and remove duplicate presets
        echo "Checking for generated files after conan install..."

        # Check all possible build directory locations
        if [ -d "build/Release/generators" ]; then
          echo "Found build/Release/generators"
          cp build/Release/generators/CMakePresets.json . 2>/dev/null || true
          cp build/Release/generators/conan_toolchain.cmake . 2>/dev/null || true
          rm -f CMakeUserPresets.json 2>/dev/null || true
        elif [ -d "build/Debug/generators" ]; then
          echo "Found build/Debug/generators"
          cp build/Debug/generators/CMakePresets.json . 2>/dev/null || true
          cp build/Debug/generators/conan_toolchain.cmake . 2>/dev/null || true
          rm -f CMakeUserPresets.json 2>/dev/null || true
        else
          echo "No generators directory found, listing build directory contents:"
          ls -la build/ 2>/dev/null || echo "No build directory found"
          find . -name "CMakePresets.json" -type f 2>/dev/null || echo "No CMakePresets.json files found anywhere"
        fi

        echo "Current directory contents after copying:"
        ls -la CMake* 2>/dev/null || echo "No CMake files in current directory"

    # Setup CMake
    - name: Configure CMake
      run: |
        preset_name="conan-release"
        build_dir="build/Release"
        if [ "${{ matrix.build_type }}" == "Debug" ]; then
          preset_name="conan-debug"
          build_dir="build/Debug"
        fi

        # Debug: Check if CMakePresets.json already exists from previous step
        echo "Checking if CMakePresets.json exists from previous step:"
        ls -la CMakePresets.json 2>/dev/null || echo "CMakePresets.json not found in root"

        # If not found, try to find and copy it
        if [ ! -f "CMakePresets.json" ]; then
          echo "CMakePresets.json not found, searching for it..."
          find . -name "CMakePresets.json" -type f 2>/dev/null | head -5

          # Try to copy from the expected location
          if [ -f "$build_dir/generators/CMakePresets.json" ]; then
            echo "Found CMakePresets.json at $build_dir/generators/, copying..."
            cp $build_dir/generators/CMakePresets.json .
            cp $build_dir/generators/conan_toolchain.cmake . 2>/dev/null || true
            rm -f CMakeUserPresets.json 2>/dev/null || true
          else
            echo "ERROR: CMakePresets.json not found at $build_dir/generators/CMakePresets.json"
            echo "All CMakePresets.json files in repository:"
            find . -name "CMakePresets.json" -type f 2>/dev/null || echo "None found"
            exit 1
          fi
        fi

        # Final verification
        echo "Final verification - CMake files in root:"
        ls -la CMakePresets.json CMakeUserPresets.json conan_toolchain.cmake 2>/dev/null || echo "Some files missing"

        # Debug: Check include directory structure
        echo "=== Debug: Project structure ==="
        echo "Current directory: $(pwd)"
        echo "Include directory contents:"
        ls -la include/ 2>/dev/null || echo "include directory not found"
        echo "Config header check:"
        ls -la include/docker-cpp/config/ 2>/dev/null || echo "config include directory not found"
        echo "Source directory contents:"
        ls -la src/config/ 2>/dev/null || echo "src/config directory not found"
        echo "=== End Debug ==="

        # Use CMake preset from root directory
        echo "Running CMake with preset: $preset_name"
        cmake --preset $preset_name -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    # Build
    - name: Build
      run: |
        preset_name="conan-release"
        build_dir="build/Release"
        if [ "${{ matrix.build_type }}" == "Debug" ]; then
          preset_name="conan-debug"
          build_dir="build/Debug"
        fi
        # Build in the correct directory
        cd $build_dir
        cmake --build . --config ${{ matrix.build_type }} --parallel $(nproc 2>/dev/null || sysctl -n hw.ncpu || echo 4)

    # Test
    - name: Test
      run: |
        preset_name="conan-release"
        build_dir="build/Release"
        if [ "${{ matrix.build_type }}" == "Debug" ]; then
          preset_name="conan-debug"
          build_dir="build/Debug"
        fi
        # Run tests in the correct directory
        cd $build_dir
        ./tests/tests-core && ./tests/tests-namespace && ./tests/tests-cgroup && ./tests/tests-plugin && ./tests/tests-config && ./tests/tests-integration

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.build_type == 'Release'
      with:
        name: docker-cpp-${{ runner.os }}-${{ matrix.arch }}
        path: |
          build/src/docker-cpp*
          build/src/*.a
          build/src/*.so
          build/src/*.dylib
          build/src/*.dll
        retention-days: 30

  # Code quality checks
  code-quality:
    name: Code Quality
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-15 clang-tidy-15 cppcheck
        python -m pip install --upgrade pip
        pip install conan==2.0.16

    - name: Create Conan profile
      run: |
        conan profile detect --force

        # Create custom profile
        echo '[settings]' > custom_profile
        echo "os=Linux" >> custom_profile
        echo "arch=x86_64" >> custom_profile
        echo "compiler=gcc" >> custom_profile
        echo "compiler.version=11" >> custom_profile
        echo "compiler.cppstd=20" >> custom_profile
        echo "compiler.libcxx=libstdc++11" >> custom_profile
        echo "build_type=Release" >> custom_profile
        echo '' >> custom_profile
        echo '[conf]' >> custom_profile
        echo 'tools.cmake.cmaketoolchain:generator=Ninja' >> custom_profile

    - name: Install dependencies
      run: |
        conan install . --build=missing --profile:build=custom_profile --profile:host=custom_profile

        # Copy CMakePresets and conan_toolchain to root directory
        if [ -d "build/Release/generators" ]; then
          cp build/Release/generators/CMakePresets.json . 2>/dev/null || true
          cp build/Release/generators/conan_toolchain.cmake . 2>/dev/null || true
          rm -f CMakeUserPresets.json 2>/dev/null || true
        fi

    - name: Generate compilation database
      run: |
        cmake --preset conan-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Check code formatting
      run: |
        find src include tests -name '*.cpp' -o -name '*.hpp' | xargs clang-format-15 --dry-run --Werror

    - name: Run static analysis
      run: |
        # Run clang-tidy in parallel with optimized settings
        # Skip tests for faster CI/CD, focus on core source files
        find src include -name '*.cpp' -o -name '*.hpp' | \
          xargs -P $(nproc) -I {} clang-tidy-15 -p build/Release {} --quiet --warnings-as-errors='*'

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction:src/test_runner.cpp \
          --suppress=preprocessorErrorDirective:src/config/config_manager.cpp \
          --suppress=unusedVariable:src/core/logger.cpp \
          --suppress=unusedVariable:src/plugin/plugin_registry.cpp \
          --suppress=unassignedVariable:src/plugin/plugin_registry.cpp \
          include/ src/

  # Security scan
  security-scan:
    name: Security Scan
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Code coverage
  coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan==2.0.16
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: Create Conan profile
      run: |
        conan profile detect --force
        conan install . --build=missing -s:h build_type=Debug

    - name: Build with coverage
      run: |
        # Copy CMakePresets and conan_toolchain to root directory
        if [ -d "build/Debug/generators" ]; then
          cp build/Debug/generators/CMakePresets.json . 2>/dev/null || true
          cp build/Debug/generators/conan_toolchain.cmake . 2>/dev/null || true
          rm -f CMakeUserPresets.json 2>/dev/null || true
        fi

        # Configure from root directory
        cmake --preset conan-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

        # Build and test in build directory
        cd build/Debug
        cmake --build . --parallel

    - name: Run tests
      run: |
        # Change to build directory and run tests
        cd build/Debug
        ./tests/tests-core && ./tests/tests-namespace && ./tests/tests-cgroup && ./tests/tests-plugin && ./tests/tests-config && ./tests/tests-integration

    - name: Generate coverage report
      run: |
        # Change to build directory and generate coverage report
        cd build/Debug
        gcovr --xml --output ../../coverage.xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  # Release (only on main branch)
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [build-and-test, code-quality, security-scan, coverage]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan==2.0.16

    - name: Create release build
      run: |
        conan profile detect --force
        conan install . --build=missing -s:h build_type=Release

        # Copy CMakePresets and conan_toolchain to root directory
        if [ -d "build/Release/generators" ]; then
          cp build/Release/generators/CMakePresets.json . 2>/dev/null || true
          cp build/Release/generators/conan_toolchain.cmake . 2>/dev/null || true
          rm -f CMakeUserPresets.json 2>/dev/null || true
        fi

        # Verify CMakePresets.json was copied
        if [ ! -f "CMakePresets.json" ]; then
          echo "ERROR: CMakePresets.json not found in root directory"
          exit 1
        fi

        # Configure from root directory
        cmake --preset conan-release -DCMAKE_BUILD_TYPE=Release

        # Check what files were created
        echo "Listing build/Release directory contents:"
        ls -la build/Release/

        # Verify CMakeCache.txt was created
        if [ ! -f "build/Release/CMakeCache.txt" ]; then
          echo "ERROR: CMakeCache.txt not found after configuration"
          echo "Available files in build/Release:"
          find build/Release -type f -name "*.txt" -o -name "*.cmake" -o -name "Makefile" | head -10
          exit 1
        fi

        # Build and package in build directory
        cd build/Release
        cmake --build . --parallel

    - name: Create packages
      run: |
        # Go to build/Release directory where CMakeCache.txt and CPackConfig.cmake are located
        cd build/Release
        echo "Running CPack from build/Release directory..."
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la

        # Debug: Check CPackConfig.cmake content
        echo "CPackConfig.cmake content:"
        grep -E "CPACK_PACKAGE_NAME|CPACK_PACKAGE_VERSION" CPackConfig.cmake || echo "Package info not found in CPackConfig.cmake"

        # Debug: Check CMakeCache.txt for project info
        echo "CMakeCache.txt project info:"
        grep -E "CMAKE_PROJECT_NAME|PROJECT_NAME" CMakeCache.txt || echo "Project name not found in CMakeCache.txt"

        # Try running CPack with verbose output
        cpack --verbose -G DEB
        cpack --verbose -G RPM
        cpack --verbose -G TGZ

    - name: Generate release notes
      id: release_notes
      run: |
        # Generate release notes from git history
        git log --oneline --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD > release_notes.txt
        echo "release_notes<<EOF" >> $GITHUB_OUTPUT
        cat release_notes.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: |
          ## Docker-CPP Release ${{ github.ref_name }}

          ${{ steps.release_notes.outputs.release_notes }}

          ### Installation

          #### Ubuntu/Debian
          ```bash
          wget https://github.com/docker-cpp/docker-cpp/releases/download/${{ github.ref_name }}/docker-cpp_${{ github.ref_name }}-1_amd64.deb
          sudo dpkg -i docker-cpp_${{ github.ref_name }}-1_amd64.deb
          ```

          #### CentOS/RHEL
          ```bash
          wget https://github.com/docker-cpp/docker-cpp/releases/download/${{ github.ref_name }}/docker-cpp-${{ github.ref_name }}-1.x86_64.rpm
          sudo rpm -i docker-cpp-${{ github.ref_name }}-1.x86_64.rpm
          ```

          #### Generic Linux
          ```bash
          wget https://github.com/docker-cpp/docker-cpp/releases/download/${{ github.ref_name }}/docker-cpp-${{ github.ref_name }}-Linux.tar.gz
          tar -xzf docker-cpp-${{ github.ref_name }}-Linux.tar.gz
          sudo cp -r docker-cpp-${{ github.ref_name }}/* /usr/local/
          ```
        files: |
          build/packages/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}